Repository xybor/xyauth, pull requests merged in 2023-01, with the labels that each got.

#11 Add DOCKER_RUNNING env to Dockfile
  .env.example
  build/Dockerfile
Labels: bug

#13 Containerize application with docker
  .dockerignore
  build/Dockerfile
Labels: enhancement

#15 Apply xypriv, add unittest
  .env.example
  .github/workflows/test.yml
  .gitignore
  README.md
  cmd/database/drop/drop.go
  cmd/database/main.go
  cmd/server/main.go
  cmd/template/main.go
  configs/compose.ini
  configs/default.ini
  deploy/compose.yaml.template
  go.mod
  go.sum
  internal/config/config.go
  internal/database/mongodb.go
  internal/database/postgresql.go
  internal/handlers/api/v1/refresh.go
  internal/handlers/api/v1/register.go
  internal/handlers/api/v1/revoke.go
  internal/handlers/app/v1/login.go
  internal/handlers/app/v1/logout.go
  internal/handlers/app/v1/refresh.go
  internal/handlers/app/v1/register.go
  internal/handlers/app/v1/welcome.go
  internal/handlers/well_known/openid/handler.go
  internal/logger/logger.go
  internal/middlewares/auth.go
  internal/models/client.go
  internal/models/error.go
  internal/models/refresh_token.go
  internal/models/schema.go
  internal/models/user.go
  internal/models/user_credential.go
  internal/router/router.go
  internal/server/server.go
  internal/utils/init.go
  internal/utils/redirect.go
  internal/utils/utils.go
  pkg/service/authentication.go
  pkg/service/refresh_token.go
  pkg/service/register.go
  pkg/token/access_token.go
  pkg/token/refresh_token.go
  pkg/token/token.go
  test/mock.go
  test/test_service/authentication_test.go
  test/test_service/register_test.go
  test/unittest/register_test.go
  web/template/register.html
Labels: enhancement

#22 Login page will redirect to the main page if user already authenticated
  internal/handlers/app/v1/login.go
Labels: enhancement

#23 Fix login not redirect to the main page when user already authenticated
  internal/handlers/app/v1/login.go
  internal/utils/utils.go
Labels: bug

#25 Allow redirecting to HTTPS if user access via HTTP
  build/Dockerfile
  cmd/server/main.go
  configs/default.ini
  deploy/compose.yaml.template
  go.mod
  go.sum
  internal/handlers/well_known/openid/handler.go
  internal/router/http.go
  internal/router/https.go
  internal/server/http.go
  internal/server/https.go
Labels: enhancement

#27 Add one-time refresh token
  README.md
  internal/handlers/api/v1/auth.go
  internal/handlers/api/v1/refresh.go
  internal/handlers/api/v1/register.go
  internal/handlers/api/v1/revoke.go
  internal/handlers/app/v1/login.go
  internal/handlers/app/v1/logout.go
  internal/handlers/app/v1/refresh.go
  internal/middlewares/auth.go
  internal/models/refresh_token.go
  internal/router/https.go
  internal/token/access_token.go
  internal/token/config.go
  internal/token/error.go
  internal/token/refresh_token.go
  internal/token/token.go
  internal/utils/cookie.go
  internal/utils/random.go
  internal/utils/utils.go
  pkg/service/authentication.go
  pkg/service/error.go
  pkg/service/refresh_token.go
Labels: enhancement

#28 Set access token as the bearer token in authorization header
  internal/handlers/api/v1/auth.go
  internal/handlers/api/v1/refresh.go
  internal/handlers/api/v1/register.go
  internal/handlers/api/v1/revoke.go
  internal/middlewares/auth.go
  internal/models/user.go
Labels: enhancement

#31 Allow adding additional configs from s3
  .env.example
  .gitignore
  build/Dockerfile
  configs/default.ini
  deploy/compose.yaml.template
  go.mod
  go.sum
  internal/config/config.go
Labels: enhancement

#33 Allow using existing database instead of standalone
  .gitignore
  Makefile
  README.md
  configs/10-default.ini
  configs/20-compose.ini
  deploy/compose.yaml.template
  go.mod
  go.sum
  internal/config/config.go
  internal/database/mongodb.go
  internal/utils/s3.go
Labels: enhancement

#35 Add custom logger
  internal/middlewares/logger.go
  internal/middlewares/recovery.go
  internal/router/http.go
  internal/router/https.go
  internal/utils/random.go
Labels: enhancement

#42 Implement user page
  README.md
  build/Dockerfile
  internal/handlers/api/v1/auth.go
  internal/handlers/api/v1/refresh.go
  internal/handlers/api/v1/revoke.go
  internal/handlers/app/v1/login.go
  internal/handlers/app/v1/logout.go
  internal/handlers/app/v1/refresh.go
  internal/handlers/app/v1/user.go
  internal/handlers/app/v1/welcome.go
  internal/logger/logger.go
  internal/middlewares/auth.go
  internal/middlewares/logger.go
  internal/models/client.go
  internal/models/refresh_token.go
  internal/models/schema.go
  internal/models/user.go
  internal/models/user_credential.go
  internal/router/https.go
  internal/token/access_token.go
  internal/token/config.go
  internal/token/refresh_token.go
  internal/utils/redirect.go
  internal/utils/utils.go
  pkg/service/authentication.go
  pkg/service/error.go
  pkg/service/refresh_token.go
  pkg/service/register.go
  pkg/service/user.go
  test/mock.go
  test/test_service/authentication_test.go
  test/test_service/register_test.go
  web/template/profile.html
  web/template/register.html
  web/template/welcome.html
Labels: enhancement

#43 Update expiration when a new refresh token is inherited
  pkg/service/refresh_token.go
Labels: bug

#45 Certificates and keys should be stored on s3
  .env.example
  CHANGELOG.md
  configs/10-default.ini
  deploy/compose.yaml.template
  internal/certificate/cert.go
  internal/cloud/s3.go
  internal/database/mongodb.go
  internal/server/https.go
  internal/token/token.go
Labels: enhancement

#46 Add architecture image
  README.md
  assets/aws.drawio.svg
Labels: documentation

#49 Use 303 See Other instead of 301 Moved Permanent to avoid caching
  internal/handlers/app/v1/login.go
  internal/handlers/app/v1/logout.go
  internal/handlers/app/v1/refresh.go
  internal/handlers/app/v1/user.go
Labels: enhancement
